import React,{useEffect,useRef,useState} from 'react';
import {prepareAudio,playCardSound,playShuffleSound} from './sound.js';
const cardEdges=()=>[1,2,3,4,5,6,7,8].map(depth=><span key={depth} className="card-edge" style={{"--depth":depth}}/>);
export default function CardDraw({revealed,onReveal,reduced,sound,name,companion,children}){
 const [phase,setPhase]=useState(revealed?'revealed':'shuffle'),[celebrate,setCelebrate]=useState(false);
 const locked=useRef(false),timer=useRef(null),shineTimer=useRef(null),gesture=useRef(null),returnTimer=useRef(null),button=useRef(null);
 useEffect(()=>()=>{clearTimeout(timer.current);clearTimeout(shineTimer.current);clearTimeout(returnTimer.current);},[]);
 useEffect(()=>{if(phase!=='shuffle'||!sound)return;let live=true;void prepareAudio().then(()=>{if(live)playShuffleSound();});const id=setInterval(playShuffleSound,150);return()=>{live=false;clearInterval(id);};},[phase,sound]);
 function draw(){if(locked.current)return;locked.current=true;setPhase('flip');button.current?.classList.add('lifting');if(sound)void prepareAudio().then(()=>playCardSound());timer.current=setTimeout(()=>{onReveal();setCelebrate(true);setPhase('revealed');if(sound)playCardSound();shineTimer.current=setTimeout(()=>setCelebrate(false),1000);},reduced?100:950);}
 function begin(e){if(phase!=='shuffle'||locked.current||gesture.current)return;clearTimeout(returnTimer.current);gesture.current={pointerId:e.pointerId,y:e.clientY,threshold:Math.min(180,Math.max(110,e.currentTarget.clientHeight*.5))};e.currentTarget.setPointerCapture(e.pointerId);e.currentTarget.classList.add('dragging','lifting');}
 function move(e){const g=gesture.current;if(!g||g.pointerId!==e.pointerId||locked.current)return;const distance=Math.max(0,g.y-e.clientY);e.currentTarget.style.setProperty('--pull',`${Math.min(distance,g.threshold+12)}px`);if(distance>=g.threshold){gesture.current=null;e.currentTarget.classList.remove('dragging');draw();}}
 function resetPull(e){if(locked.current)return;gesture.current=null;e.currentTarget.classList.remove('dragging');e.currentTarget.style.setProperty('--pull','0px');const node=e.currentTarget;returnTimer.current=setTimeout(()=>node.classList.remove('lifting'),300);}
 if(phase==='revealed'||revealed)return <div className={`card-revealed ${celebrate?'companion-celebrates':''}`}><div className={`draw-companion ${celebrate?'celebrating':''}`} aria-hidden="true">{companion}</div>{celebrate&&<div className="card-sparkles" aria-hidden="true">{Array.from({length:8},(_,i)=><i key={i} style={{'--angle':`${i*45}deg`,'--delay':`${i%3*40}ms`}}/>)}</div>}{children}</div>;
 return <div className={`draw-experience ${phase}`}><div className="draw-companion" aria-hidden="true">{companion}</div><p className="draw-owner">{name}</p><button ref={button} className="draw-hitbox" onPointerDown={begin} onPointerMove={move} onPointerUp={resetPull} onPointerCancel={resetPull} onClick={e=>{if(e.detail===0)draw();}} disabled={phase==='flip'} aria-label="向上滑动抽出烧烧卡，键盘可按回车"><span className="shuffling-deck" aria-hidden="true">{[0,1,2,3].map(i=><span className="draw-back" key={i} style={{'--i':i}}>{cardEdges()}<b>SAO</b><small>烧烧卡</small></span>)}</span><span className="picked-card" aria-hidden="true">{cardEdges()}<b>SAO</b><small>烧烧卡</small></span></button><p className="draw-prompt" aria-live="polite">{phase==='shuffle'?'↑ 向上抽出卡牌':'就是这张！'}</p></div>;
}
