import test from 'node:test';import assert from 'node:assert/strict';import * as E from './engine.js';import {SAVE_KEY,readGame,writeGame,packSave,unpackSave} from './save-store.js';
function store(limit=Infinity){let raw=null;return {getItem:()=>raw,setItem:(key,value)=>{if(value.length>limit){const e=new Error('full');e.name='QuotaExceededError';throw e;}raw=value;}};}
function state(){const s=E.fresh();E.addPlayer(s,'测试角色');return s;}
test('容量不足仅缩减较早撤销记录，完整状态与本轮备份保留并可重开',()=>{const s=state();s.round=2;s.roundCheckpoint={...E.clone(s),round:1};const base=JSON.stringify({state:s,history:[],rev:1}).length,storage=store(base*3);const saved=writeGame(storage,{state:s,history:Array(20).fill(E.clone(s)),rev:1},null);assert(saved.trimmed);assert(saved.history.length<20);assert.deepEqual(saved.state,s);assert.equal(readGame(storage).state.round,2);});
test('即使零撤销也写不下，旧存档保持字节不变',()=>{const storage=store(100000);const original=writeGame(storage,{state:state(),history:[],rev:1},null);const large=state();large.log=Array.from({length:100},()=>({text:'x'.repeat(2000),time:new Date().toISOString()}));assert.throws(()=>writeGame(storage,{state:large,history:[],rev:2},original.storedRaw));assert.equal(storage.getItem(SAVE_KEY),original.storedRaw);});
test('一份撤销损坏不抹掉有效当前第二轮，不重写原始数据',()=>{const storage=store();const s=state();s.round=2;const raw=JSON.stringify({state:s,history:[state(),{bad:true}],rev:4});storage.setItem(SAVE_KEY,raw);const loaded=readGame(storage);assert.equal(loaded.state.round,2);assert.equal(loaded.history.length,1);assert(loaded.warning);assert.equal(storage.getItem(SAVE_KEY),raw);});
test('损坏主存档保留原始字节并阻止普通操作，读取不触发写入',()=>{const storage=store();storage.setItem(SAVE_KEY,'{broken');const loaded=readGame(storage);assert(loaded.readFailed);assert.equal(loaded.storedRaw,'{broken');assert.equal(storage.getItem(SAVE_KEY),'{broken');});
test('不同窗口更新后禁止陈旧覆盖，包括撤销与导入',()=>{const storage=store();const first=writeGame(storage,{state:state(),history:[],rev:1},null);const other=writeGame(storage,{state:state(),history:[],rev:2},first.storedRaw);assert.throws(()=>writeGame(storage,{state:state(),history:[],rev:3},first.storedRaw),{name:'SaveConflictError'});assert.equal(storage.getItem(SAVE_KEY),other.storedRaw);});
test('非容量错误不丢弃撤销，不清除任何存档',()=>{let calls=0;const storage={getItem:()=>null,setItem:()=>{calls++;const e=new Error('denied');e.name='SecurityError';throw e;}};assert.throws(()=>writeGame(storage,{state:state(),history:[state()],rev:1},null),{name:'SecurityError'});assert.equal(calls,1);});

test('头像在当前、回合备份及20份撤销中只保存一次，往返无损',()=>{const s=state();s.players[0].avatar='data:image/jpeg;base64,'+'A'.repeat(8000);const envelope={state:s,history:Array.from({length:20},()=>E.clone(s)),rev:1};const packed=packSave(envelope);assert.equal(JSON.parse(packed).images.length,1);assert(packed.length<JSON.stringify(envelope).length/4);assert.deepEqual(unpackSave(JSON.parse(packed)),envelope);const storage=store();storage.setItem(SAVE_KEY,packed);assert.equal(readGame(storage).state.players[0].avatar,s.players[0].avatar);});
test('损坏头像引用保留原始数据，不自动清空',()=>{const storage=store();storage.setItem(SAVE_KEY,JSON.stringify({format:'life-island-compact-v2',images:[],payload:{state:{players:[{avatar:{image:2}}]}}}));assert(readGame(storage).readFailed);assert(storage.getItem(SAVE_KEY));});
